---
title: "Awards"
description: |
  Record of awards for the ISSC Case Competition
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

If you have any questions or would like to verify a student's participation, please reach out to the Case Competition Faculty Coordinator, Prof. Samantha-Jo Caetano at [s.caetano\@utoronto.ca](mailto:s.caetano@utoronto.ca){.email}.

# 2021

+--------------------------+--------------------------------+---------------------------+-----------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Category                 | Award                          | Team Name                 | Team members                                  | Judges comments                                                                                                                                                                                                                                                                                                                                                        |
+==========================+================================+===========================+===============================================+========================================================================================================================================================================================================================================================================================================================================================================+
| Most Creative Data/Topic | Honourable Mention             | Random Error              | Zihao Guo,                                    | This team conducted a survey to identify which indicators were important to people for judging livability and tailored their investigation to healthcare based on these findings.                                                                                                                                                                                      |
|                          |                                |                           | Yujin Liu,                                    |                                                                                                                                                                                                                                                                                                                                                                        |
|                          |                                |                           | Jialei Cai,                                   |                                                                                                                                                                                                                                                                                                                                                                        |
|                          |                                |                           | Yingcong Zuo                                  |                                                                                                                                                                                                                                                                                                                                                                        |
+--------------------------+--------------------------------+---------------------------+-----------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Most Creative Data/Topic | Winner                         | Zero Point Five           | Yi                                            | This team had investigated multiple aspects of livability in Toronto. Two of which really stood out were the investigation of air quality and childcare.                                                                                                                                                                                                               |
|                          |                                |                           | Qin, Pan Chen, Yini Mao,                      |                                                                                                                                                                                                                                                                                                                                                                        |
|                          |                                |                           | Xiaoxuan Han                                  |                                                                                                                                                                                                                                                                                                                                                                        |
+--------------------------+--------------------------------+---------------------------+-----------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Best Presentation        | Honourable Mention (Dashboard) | EKPY                      | Younwoo                                       | This team developed a dashboard in Tableaux allowing users to browse neighbourhoods on several measures.                                                                                                                                                                                                                                                               |
|                          |                                |                           | Choi, Prashant Patel, Yilin Huang, Kevin Wang |                                                                                                                                                                                                                                                                                                                                                                        |
+--------------------------+--------------------------------+---------------------------+-----------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Best Presentation        | Winner (Slides)                | Statistically Significant | José                                          | This team was voted Best Presentation by all judges. Great usage of self-explanatory graphics. All team members spoke in the video presentation and all speakers were well paced and spoke very clearly.                                                                                                                                                               |
|                          |                                |                           | Casas, Janhavi                                |                                                                                                                                                                                                                                                                                                                                                                        |
|                          |                                |                           | Agarwal, Aliza Aziz Lakho, Xiaoke             |                                                                                                                                                                                                                                                                                                                                                                        |
|                          |                                |                           | Jiang                                         |                                                                                                                                                                                                                                                                                                                                                                        |
+--------------------------+--------------------------------+---------------------------+-----------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Best Insight             | Honourable Mention             | Super Sonic               | Siqi                                          | Firstly, the land acknowledgement is a great addition. This group investigated livability from an international students' perspective. Looking at crime rate, rent, food prices, social/transportation, and using in depth methods they were able to assess how liveable Toronto is. Great visualizations, we especially like the web graphic for grocery item prices. |
|                          |                                |                           | Zheng, Haining Tan,                           |                                                                                                                                                                                                                                                                                                                                                                        |
|                          |                                |                           | Xiao Wu                                       |                                                                                                                                                                                                                                                                                                                                                                        |
+--------------------------+--------------------------------+---------------------------+-----------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Best Insight             | Winner                         | Prospective               | Eric                                          | Good usage of the economics livability score (an already validated measure of livability). Their methods looked at: Stability, Healthcare, education, infrastructure, culture/environment by Toronto neighbourhoods. Using external data, they invoked senior level methods to investigate livability. Also, great job mentioning limitations and next steps.          |
|                          |                                | Analytics                 | Zhu, Jing Yuan Zhang, Sergio                  |                                                                                                                                                                                                                                                                                                                                                                        |
|                          |                                |                           | Zheng Zhou, Muhammad Tsany                    |                                                                                                                                                                                                                                                                                                                                                                        |
+--------------------------+--------------------------------+---------------------------+-----------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
